[2024-11-09T18:58:38.119+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-09T18:58:38.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_atlas_fetch_load_data.load_data manual__2024-11-09T18:57:43.199995+00:00 [queued]>
[2024-11-09T18:58:38.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_atlas_fetch_load_data.load_data manual__2024-11-09T18:57:43.199995+00:00 [queued]>
[2024-11-09T18:58:38.180+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-09T18:58:38.209+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2024-11-09 18:57:43.199995+00:00
[2024-11-09T18:58:38.230+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=346) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-09T18:58:38.234+0000] {standard_task_runner.py:72} INFO - Started process 348 to run task
[2024-11-09T18:58:38.241+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mongodb_atlas_fetch_load_data', 'load_data', 'manual__2024-11-09T18:57:43.199995+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/et_pipeline.py', '--cfg-path', '/tmp/tmpcfdj4qv6']
[2024-11-09T18:58:38.245+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask load_data
[2024-11-09T18:58:38.387+0000] {task_command.py:467} INFO - Running <TaskInstance: mongodb_atlas_fetch_load_data.load_data manual__2024-11-09T18:57:43.199995+00:00 [running]> on host c81164041ce5
[2024-11-09T18:58:38.958+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mongodb_atlas_fetch_load_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T18:57:43.199995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T18:57:43.199995+00:00'
[2024-11-09T18:58:38.970+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-09T18:58:38.974+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-09T18:58:38.975+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-11-09 18:58:38.162295+00:00
[2024-11-09T18:58:38.976+0000] {logging_mixin.py:190} INFO - Dag name:mongodb_atlas_fetch_load_data and current dag run status:running
[2024-11-09T18:58:38.977+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-09T18:58:38.979+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_pipeline.py", line 86, in <lambda>
    python_callable=lambda **kwargs: gcp_load(fetch_data_task.output, **kwargs),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_pipeline.py", line 49, in gcp_load
    "sourceUris": [f"gs://my-bucket-name/{os.path.basename(file_path)}"],
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 171, in basename
TypeError: expected str, bytes or os.PathLike object, not PlainXComArg
[2024-11-09T18:58:39.028+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-09T18:58:39.029+0000] {logging_mixin.py:190} INFO - Task start:2024-11-09 18:58:38.162295+00:00 end:2024-11-09 18:58:39.026922+00:00 duration:0.864627
[2024-11-09T18:58:39.031+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data> dag:<DAG: mongodb_atlas_fetch_load_data> dagrun:<DagRun mongodb_atlas_fetch_load_data @ 2024-11-09 18:57:43.199995+00:00: manual__2024-11-09T18:57:43.199995+00:00, state:running, queued_at: 2024-11-09 18:57:43.237812+00:00. externally triggered: True>
[2024-11-09T18:58:39.036+0000] {logging_mixin.py:190} INFO - Failure caused by expected str, bytes or os.PathLike object, not PlainXComArg
[2024-11-09T18:58:39.036+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mongodb_atlas_fetch_load_data, task_id=load_data, run_id=manual__2024-11-09T18:57:43.199995+00:00, execution_date=20241109T185743, start_date=20241109T185838, end_date=20241109T185839
[2024-11-09T18:58:39.163+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-09T18:58:39.169+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 78 for task load_data (expected str, bytes or os.PathLike object, not PlainXComArg; 348)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_pipeline.py", line 86, in <lambda>
    python_callable=lambda **kwargs: gcp_load(fetch_data_task.output, **kwargs),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/et_pipeline.py", line 49, in gcp_load
    "sourceUris": [f"gs://my-bucket-name/{os.path.basename(file_path)}"],
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 171, in basename
TypeError: expected str, bytes or os.PathLike object, not PlainXComArg
[2024-11-09T18:58:39.241+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-09T18:58:39.387+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-09T18:58:39.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
